"""
Phase A migration — drop Excel-cruft columns and tighten the schema.

Drops from `monsters`:
    cr_text             — duplicates challenge_rating (REAL)
    all_feats           — equals `feats + ", " + bonus_feats` (recomputed at runtime)
    stat_block          — generated by the calculator on demand
    bonus_feat_count    — counter on `bonus_feats` text (recomputed at runtime)
    max_adv_base_size   — Excel-parsed advancement bound (router validation removed)
    max_adv_next_size   — Excel-parsed advancement bound
    reach2, reach2_desc, is_reach2_reach_weapon, reach3, reach3_desc
                        — never read; per-attack reach lives on `attacks.reach` instead

Renames in `monsters`:
    reach1 → reach      — match the SRD canonical schema (single column)

Adds to `attacks`:
    reach TEXT          — per-attack reach for asymmetric creatures (Tall+Long mix)

This script is idempotent: running it twice is a no-op (it checks the
current schema first).

Usage:
    python backend/data/migrate_phase_a.py
"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent / "monsters.db"

NEW_MONSTERS_COLUMNS = [
    "id", "name", "size", "type", "descriptor",
    "hd_count", "hit_dice", "initiative", "speed", "armor_class",
    "base_attack", "grapple", "attack", "full_attack",
    "space", "reach",
    "special_attacks", "special_qualities",
    "skills", "feats", "bonus_feats", "saves",
    "fort_save_type", "ref_save_type", "will_save_type",
    "str", "dex", "con", "int", "wis", "cha",
    "environment", "organization", "challenge_rating",
    "treasure", "alignment", "advancement",
    "special_abilities", "reference",
    "level_adjustment", "altname",
]

CREATE_MONSTERS_NEW = """
CREATE TABLE monsters_new (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    size TEXT,
    type TEXT,
    descriptor TEXT,
    hd_count INTEGER,
    hit_dice TEXT,
    initiative TEXT,
    speed TEXT,
    armor_class TEXT,
    base_attack INTEGER,
    grapple TEXT,
    attack TEXT,
    full_attack TEXT,
    space TEXT,
    reach TEXT,
    special_attacks TEXT,
    special_qualities TEXT,
    skills TEXT,
    feats TEXT,
    bonus_feats TEXT,
    saves TEXT,
    fort_save_type TEXT,
    ref_save_type TEXT,
    will_save_type TEXT,
    str INTEGER,
    dex INTEGER,
    con INTEGER,
    int INTEGER,
    wis INTEGER,
    cha INTEGER,
    environment TEXT,
    organization TEXT,
    challenge_rating REAL,
    treasure TEXT,
    alignment TEXT,
    advancement TEXT,
    special_abilities TEXT,
    reference TEXT,
    level_adjustment TEXT,
    altname TEXT
)
"""


def migrate(con: sqlite3.Connection) -> None:
    cur = con.cursor()

    cur.execute("PRAGMA table_info(monsters)")
    monster_cols = {row[1] for row in cur.fetchall()}

    # Idempotency guard: nothing to do if reach1 is gone and reach exists.
    if "reach1" not in monster_cols and "reach" in monster_cols:
        print("monsters table already migrated — skipping")
    else:
        print("Rebuilding monsters table without redundant columns ...")
        cur.execute(CREATE_MONSTERS_NEW)
        # Note: reach1 → reach in the column list; everything else copies straight.
        cur.execute("""
            INSERT INTO monsters_new (
                id, name, size, type, descriptor,
                hd_count, hit_dice, initiative, speed, armor_class,
                base_attack, grapple, attack, full_attack,
                space, reach,
                special_attacks, special_qualities,
                skills, feats, bonus_feats, saves,
                fort_save_type, ref_save_type, will_save_type,
                str, dex, con, int, wis, cha,
                environment, organization, challenge_rating,
                treasure, alignment, advancement,
                special_abilities, reference, level_adjustment, altname
            )
            SELECT
                id, name, size, type, descriptor,
                hd_count, hit_dice, initiative, speed, armor_class,
                base_attack, grapple, attack, full_attack,
                space, reach1,
                special_attacks, special_qualities,
                skills, feats, bonus_feats, saves,
                fort_save_type, ref_save_type, will_save_type,
                str, dex, con, int, wis, cha,
                environment, organization, challenge_rating,
                treasure, alignment, advancement,
                special_abilities, reference, level_adjustment, altname
            FROM monsters
        """)
        cur.execute("DROP TABLE monsters")
        cur.execute("ALTER TABLE monsters_new RENAME TO monsters")
        cur.execute("CREATE INDEX idx_monsters_name ON monsters(name)")
        cur.execute("CREATE INDEX idx_monsters_type ON monsters(type)")

    cur.execute("PRAGMA table_info(attacks)")
    attack_cols = {row[1] for row in cur.fetchall()}
    if "reach" in attack_cols:
        print("attacks.reach column already exists — skipping")
    else:
        print("Adding attacks.reach column ...")
        # SQLite supports adding nullable columns directly.
        cur.execute("ALTER TABLE attacks ADD COLUMN reach TEXT")

    con.commit()
    print("Migration complete.")


if __name__ == "__main__":
    if not DB_PATH.exists():
        raise SystemExit(f"DB not found: {DB_PATH} — run build_db.py first")
    con = sqlite3.connect(DB_PATH)
    try:
        migrate(con)
    finally:
        con.close()
